DocWorks for js-wixcode-sdk - 57 changes detected, but 55 issue detected changes: Service $w.CheckboxGroup property options has changed type Service $w.CheckboxGroup property selectedIndices has changed type Service $w.CheckboxGroup property value has changed type Service $w.ColumnStrip property columns has changed type Service $w.ContainableMixin property children has changed type Service $w.DatePicker property disabledDates has changed type Service $w.DatePicker property disabledDaysOfWeek has changed type Service $w.Document property children has changed type Service $w.Dropdown property options has changed type Service $w.GoogleMap has a new property center Service $w.GoogleMap has a new property zoom Service $w.GoogleMap has a new property markers Service $w.MultiStateBox property states has changed type Service $w.Page property keywords has changed type Service $w.RadioButtonGroup property options has changed type Service $w.Repeater property data has changed type Service $w.Repeater operation forItems has changed param itemIds type Service $w.Slide has changed description Service $w.Slide property id has changed description Service $w.Slideshow has changed description Service $w.Slideshow property slides has changed type Service $w.Slideshow operation onChange has changed extra.notes Service $w.Table property columns has changed type Service $w.Table property rows has changed type Service $w.TextInputMixin operation onInput was removed Service $w.TextInputMixin operation onKeyPress has changed extra.notes Service $w.UploadButton property fileType has changed description Service $w.UploadButton property value has changed type Service npm-modules has changed description Service site-monitoring.LogEntry message LogEntryOperation has changed description Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes Service wix-location.QueryParams operation remove has changed param toRemove type Service wix-location property path has changed type Service wix-site operation routerSitemap has changed return type Service wix-site message PrefetchItems member pages has changed type Service wix-site message PrefetchItems member lightboxes has changed type Service wix-site message PrefetchResultError member pages has changed type Service wix-site message PrefetchResultError member lightboxes has changed type Service wix-site message SiteStructure member pages has changed type Service wix-site message SiteStructure member pages has changed doc Service wix-site message SiteStructure member prefixes has changed type Service wix-site message SiteStructure member lightboxes has changed type Service wix-storage.Storage has changed summary Service wix-storage.Storage operation setItem has changed extra.notes Service wix-storage has changed summary Service wix-storage has changed description Service wix-window.multilingual property siteLanguages has changed type Service wix-window.trackingParameters message AddProductImpressionEvent member contents has changed type Service wix-window.trackingParameters message InitiateCheckoutEvent member contents has changed type Service wix-window.trackingParameters message PurchaseEvent member contents has changed type Service wix-window operation copyToClipboard has changed return doc Service wix-window operation copyToClipboard has changed summary Service wix-window operation copyToClipboard has changed description Service wix-window operation copyToClipboard.examples[0] has changed body Service $w.HoverBox is new Service $w.VideoBox is new Service wix-events is new
issues:
Property children has an unknown type [ 'Array' ] (document.es6 (87))
Operation remove has an unknown param type [ 'Array' ] (location.es6 (281))
Property options has an unknown type [ 'Array' ] (CheckboxGroup.es6 (58))
Property options has an unknown type [ 'Array' ] (CheckboxGroup.es6 (92))
Property value has an unknown type [ 'Array' ] (CheckboxGroup.es6 (143))
Property value has an unknown type [ 'Array' ] (CheckboxGroup.es6 (173))
Property selectedIndices has an unknown type [ 'Array' ] (CheckboxGroup.es6 (211))
Property selectedIndices has an unknown type [ 'Array' ] (CheckboxGroup.es6 (239))
Property columns has an unknown type [ 'Array' ] (ColumnStrip.es6 (28))
Property disabledDates has an unknown type [ 'Array' ] (DatePicker.es6 (206))
Property disabledDates has an unknown type [ 'Array' ] (DatePicker.es6 (237))
Property disabledDaysOfWeek has an unknown type [ 'Array' ] (DatePicker.es6 (271))
Property disabledDaysOfWeek has an unknown type [ 'Array' ] (DatePicker.es6 (304))
Property options has an unknown type [ 'Array' ] (DropDown.es6 (52))
Property options has an unknown type [ 'Array' ] (DropDown.es6 (91))
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Property states has an unknown type [ 'Array' ] (MultiStateBox.es6 (208))
Property keywords has an unknown type [ 'Array' ] (Page.es6 (63))
Property options has an unknown type [ 'Array' ] (RadioButtonGroup.es6 (51))
Property options has an unknown type [ 'Array' ] (RadioButtonGroup.es6 (89))
Operation forItems has an unknown param type [ 'Array' ] (Repeater.es6 (659))
Property data has an unknown type [ 'Array' ] (Repeater.es6 (288))
Property data has an unknown type [ 'Array' ] (Repeater.es6 (387))
Property slides has an unknown type [ 'Array' ] (Slideshow.es6 (228))
Property columns has an unknown type [ 'Array' ] (Table.es6 (390))
Property columns has an unknown type [ 'Array' ] (Table.es6 (426))
Property rows has an unknown type [ 'Array' ] (Table.es6 (579))
Property rows has an unknown type [ 'Array' ] (Table.es6 (619))
Property value has an unknown type [ 'Array' ] (UploadButton.es6 (195))
Property value has an unknown type [ 'Array' ] (UploadButton.es6 (226))
Property path has an unknown type [ 'Array' ] (location.es6 (193))
Operation routerSitemap has an unknown return type [ 'Array' ] (site.es6 (101))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message PrefetchItems has an unknown property type [ 'Array' ] (site.es6 (283))
Message PrefetchItems has an unknown property type [ 'Array' ] (site.es6 (283))
Message PrefetchResultError has an unknown property type [ 'Array' ] (site.es6 (310))
Message PrefetchResultError has an unknown property type [ 'Array' ] (site.es6 (310))
Message AddProductImpressionEvent has an unknown property type [ 'Array' ] (window.es6 (731))
Message InitiateCheckoutEvent has an unknown property type [ 'Array' ] (window.es6 (814))
Message PurchaseEvent has an unknown property type [ 'Array' ] (window.es6 (839))
Property siteLanguages has an unknown type [ 'Array' ] (window.es6 (1246))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property children has an unknown type [ 'Array' ] (ContainableMixin.es6 (19))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 104
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389